version: '3.8'

services:
  # --- FRONTEND (Worker 1) ---
  # Uses the public Nginx image
  frontend:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - front-net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == worker1

  # --- BACKEND (Manager 1) ---
  # Uses the public Apache (httpd) image
  backend:
    image: httpd:latest
    networks:
      - front-net
      - back-net
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.hostname == manager1

  # --- DATABASE (Worker 2) ---
  # Uses the public Redis image
  database:
    image: redis:alpine
    networks:
      - back-net
    volumes:
      - db-data:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == worker2

networks:
  front-net:
    driver: overlay
  back-net:
    driver: overlay

volumes:
  db-data: